name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npx turbo build

      - name: Check dir existence
        run: cd apps/router
      
      - name:
        run: dir

      - name:
        run: cd dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './apps/router/dist'
